apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "medic.configmapName" . }}
  namespace: {{ include "medic.namespace" . }}
  labels:
    {{- include "medic.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
